# Generated by Django 4.2.16 on 2026-04-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_starts__b01102_idx',
            old_name='events_even_starts__b96432_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_languag_67ce95_idx',
            old_name='events_even_languag_86a4f3_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_locatio_0ae1f4_idx',
            old_name='events_even_locatio_c9b7e5_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_created_95418c_idx',
            old_name='events_even_created_2f8d12_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_starts__f14497_idx',
            old_name='events_even_starts__composite_idx',
        ),
    ]
