# Generated by Django 4.2.16 on 2026-04-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_seeker__04fd8c_idx',
            old_name='enrollments_seeker_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_event_i_f9b1eb_idx',
            old_name='enrollments_event_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_followu_0d1101_idx',
            old_name='enrollments_followup_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_reminde_74449a_idx',
            old_name='enrollments_reminder_idx',
        ),
    ]
