# Generated by Django 4.2.16 on 2026-04-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unique_email_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='users_email_user_id_155caa_idx',
            old_name='users_email_user_id_9d1c35_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='users_email_expires_63503d_idx',
            old_name='users_email_expires_7e1b0c_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='users_profi_role_0cf86e_idx',
            old_name='users_profi_role_cf5a47_idx',
        ),
    ]
